enabled 'python setup.py test' with py.test
- use http://doc.pytest.org/en/latest/goodpractices.html#manual-integration
- needed to safeguard against no additional command line options so
  added line to check if self.pytest_args are empty (otherwise dies with
  AttributeError: 'list' object has no attribute 'read' (in read token)